linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: true
    cancel_subscriptions: true
    sort_constructors_first: true
    always_declare_return_types: true
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    annotate_overrides: true
    avoid_empty_else: true
    enable_null_safety: true
    use_decorated_box: true
    unnecessary_null_checks: true
    unnecessary_await_in_return: true
    unnecessary_new: true
    await_only_futures: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_if_null_operators: true
    prefer_conditional_assignment: true
    prefer_contains: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_generic_function_type_aliases: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_inlined_adds: true
    prefer_iterable_whereType: true
    prefer_mixin: true
    prefer_null_aware_operators: true
    prefer_foreach: true
    prefer_spread_collections: true
    prefer_typing_uninitialized_variables: true
    always_use_package_imports: true
    annotate_redeclares: true
    constant_identifier_names: true
    non_constant_identifier_names: true
    avoid_dynamic_calls: true
    camel_case_types: true
    camel_case_extensions: true
    cascade_invocations: true
    avoid_redundant_argument_values: true
    use_build_context_synchronously: true
    
analyzer:
  exclude:
    - build/**
    - lib/assets.dart
    - lib/assets.preview.dart
    - lib/**.freezed.dart
    - lib/**.g.dart


